image: Visual Studio 2017
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\Library\SslLabsLib\SslLabsLib.csproj)

    $version = $doc.Project.PropertyGroup.VersionPrefix

    Update-AppveyorBuild -Version "$version build $env:APPVEYOR_BUILD_NUMBER"
- ps: # Core
- ps: msbuild /t:Restore
- ps: # Build
- ps: msbuild /t:Build /p:Configuration=Release
test: off
#test_script:
#- ps: dotnet test -c Release Library\SslLabsLib.Tests
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: dgfUEGXULcqCTyNcS6UEDK8BCBi8y+M2+d4IFjnb3Gf9DqV34fMSp1XjxJg2AVRC
  on:
    branch: nuget